Data:
    Songs_DB_Clusters: "Data/Songs_DB_Clusters.csv"

Random:
    State: 22

Transformers:
    Power: "Transformers/Power_Transformer.pkl"

Scalers:
    Standard: "Scalers/Standard_Scaler.pkl""

Models:
    K-Means: "Models/KM_28.pkl"